### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by nadheemabd** [murat-polat/tutor-wagtail#1]
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /.local/share/tutor-plugins/tutor-wagtail
message pops up when `pip3 install -e tutor-wagtail` is executed.
When navigated inside tutor-wagtail folder and executes installation command, it gets installed but on runnung tutor plugins list, the plugin is not shown in the list.

**Comment by murat-polat** [comment]
Hi @nadheemabdulla ,
Thanks for your feedback. I see, because I also faced same issue before.  Inside active virtualenv, after installation, just reboot server, you should see wagtail plugin(may be need reactivate virtualenv).  I believe the problem is Python3 libraries and (setuptools etc.). 
Please give me feedback if there is any issue. Thanks..
Murat

**Comment by murat-polat** [comment]
Just updated Readme, and added wagtail-job, after test brand new installation, it's works. Could you test it again please?
In my experience, plugins from tutor (ecommerce, discovery, minio etc.) are available always. But custom plugins like this plugin should install inside virtualenv if it's necessary. Thanks.

**Comment by murat-polat** [comment]
It's working:)
